# Generated by Django 2.2.6 on 2020-05-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
