# Generated by Django 2.2.6 on 2020-05-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200525_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(related_name='sizes', to='product.Product'),
        ),
    ]
