# Generated by Django 2.2.6 on 2020-05-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200525_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
