# Generated by Django 2.2.6 on 2020-05-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Posted_date',
            new_name='posted_date',
        ),
    ]
